export const text_properties = {
    title: {
        app: 'Excel-NG',
        ex_ante: 'EX - ANTE',
        riferimento: 'RIFERIMENTO',
        ex_post: 'EX - POST',
        veicoli_elettrici: 'Veicoli Elettrici',
        veicoli_ibridi: 'Veicoli Ibridi',
        motori: 'Motori',
        comportamentale: 'Comportamentale',
        dati: 'Dati',
        navi: 'Navi',
        compressori: 'Compressori',
        registrazione: 'Registrazione',
    },
    header: {
        sei_in: 'Sei in:',
        home: 'Home',
        next: '>>',
        certificati_bianchi: 'Certificati Bianchi',
    },
    label: {
        carica_documento: 'Carica Documento',
        si: 'Si',
        no: 'No',
        nome: 'Nome',
        cognome: 'Cognome',
        email: 'Email',
        password: 'Password',
        regioni: 'Regioni',
    },
    messaggio: {
        info: 'Info',
        attenzione: 'Attenzione',
        errore: 'Errore',
        errore_durante_richiesta: 'Si � verificato un errore nel processare la richiesta.',
        nessun_risultato_trovato: 'Nessun risultato trovato',
    },
    button: {
        apri: 'Apri',
        chiudi: 'Chiudi',
        annulla: 'Annulla',
        conferma: 'Conferma',
        entra: 'Entra',
        cerca: 'Cerca',
        modifica: 'Modifica',
        nuovo: 'Nuovo',
        salva: 'Salva',
        pulisci: 'Reset',
        dettaglio: 'Dettaglio',
        elimina: 'Elimina',
        applica: 'Applica',
        prosegui: 'Prosegui',
        indietro: 'Indietro',
        precedente: 'Precedente',
        successivo: 'Successivo',
        avanti: 'Avanti',
        ok: 'Ok',
        si: 'Si',
        no: 'No',
        cancella_filtri: 'Cancella Filtri',
        crea: 'Crea',
        sfoglia: 'Sfoglia...',
        salva_file: 'Salva File',
        download: 'Download',
        salva_esci: 'Salva Ed Esci',
        aggiungi: 'Aggiungi',
        carica: 'Carica',
        registrati: 'Registrati',
    },
    table: {
        col: {
            consumo_ex_ante: 'Consumo Ex Ante',
            consumi_ex_ante: 'Consumi Ex Ante',
            dati_ex_ante: 'Dati del progetto ex ante',
            veicoli: 'Veicoli',
            caratteristiche_combustibile: 'Caratteristiche del combustibile',
            misuratore: 'Misuratore',
            misura: 'Misura',
            definizione_consumo_nedc: 'Definizione del consumo di NEDC correlato',
            veicolo: 'Veicolo(n_progressivo)',
            marca: 'Marca',
            modello: 'Modello',
            segmento_mercato: 'Segmento di mercato',
            posti_disponibili: 'Posti disponibili',
            data_immatricolazione: 'Data di immatricolazione',
            matricola: 'Matricola',
            targa: 'Targa',
            n_telaio: 'N_di telaio',
            peso: 'Peso[t]',
            classe_emissioni: 'Classe di emissioni',
            incluso_campione_rappresentativo: 'Incluso nel campione rappresentativo(SI / NO)',
            alimentazione: 'Alimentazione',
            pci_combustibile_valore: 'PCI Combustibile valore[tep / t]',
            densita_combustibile_valore: 'Densit� Combustibile Valore[kg / l]',
            km_percorsi: 'km percorsi',
            scostamento_potenza: 'Scostamento potenza rispetto al veicolo ex post[%]',
            consumo_nedc_l: 'Consumo di NEDC correlato[l / 100 km]',
            prod_trasp: 'f <span class="log" > prod - trasp </span>',
            consumo_nedc_tep: 'Consumo di NEDC correlato[tep / km * 10 <span class="sup" > -6 </span>]',
            dati_riferimento: 'Dati riferimento',
            consumo_riferimento: 'Consumo di Riferimento',
            dati_veicoli_immatricolati: 'Dati veicoli immatricolati sul territorio nazionale',
            anno_prec_presentazione_ps: 'nell\'anno precedente alla presentazione del PS',
            cilindrata: 'Cilindrata[cm <span class="sup" > 3 </span>]',
            potenza: 'Potenza[kW]',
            share_mercato: 'Share di mercato[%]',
            fonte_dato_nedc: 'Fonte Dato NEDC',
            dati_ex_post: 'Dati del progetto ex post',
            consumi_ex_post: 'Consumi Ex Post',
            consumo_ex_post: 'Consumo Ex Post',
            tipo_installazione: 'Nuova installazione / Sostituzione / non sostituito',
            efr: 'EFR',
            etot: 'ETOT',
            efr_kwh: 'E <span class="log" > FR </span> [kWh]',
            etot_kwh: 'E <span class="log" > tot </span> [kWh]',
            id: 'ID',
            tipologia_motore: 'Tipologia di motore[matricola]',
            potenza_nominale: 'Potenza nominale[kW]',
            numero_poli: 'Numero di poli[n.]',
            classe_efficienza: 'Classe di efficienza motore[IEX]',
            rendimento_motore: 'Rendimento motore[%]',
            inverter: 'Inverter(SI / NO)',
            energia_elettrica_misurata: 'Energia elettrica misurata[kWh]',
            n: 'N.',
            rendimento_motore_ex_post: 'Rendimento motore Ex Post',
            classe_riferimento: 'Classe di riferimento',
            rendimento_riferimento: 'Rendimento di riferimento',
            id_motore_ex_ante: 'ID Motore Ex Ante',
            rendimento_ex_ante: 'Rendimento Ex Ante',
            rendimento_baseline: 'Rendimento di baseline',
            ore_funzionamento_cr: 'Ore di funzionamento misurate del CR[h]',
            coefficiente_carico_cr: 'Coefficiente di carico del CR[%]',
            dati_motori_elettrici_ex_post: 'Dati motori elettrici Ex Post',
            dati_rendimento_baseline: 'Dati per la determinazione del rendimento di baseline',
            dati_misurati_calcoli: 'Dati misurati e calcoli',
            motori: 'Motori',
            gruppo_controllo: 'Gruppo di controllo GDC',
            gruppo_trattamento: 'Gruppo di trattamento GDT',
            lista_utenze: 'Lista utenze[nome e cognome]',
            ante_gdc: 'Ante <span class="log" > GDC </span> [kWh/anno]',
            post_gdc: 'Post <span class="log" > GDC </span> [kWh/anno]',
            delta_consumi_gdc: '\u0394ConsumiGDC[kWh / anno]',
            ante_gdt: 'Ante <span class="log" > GDT </span> [kWh/anno]',
            post_gdt: 'Post <span class="log" > GDT </span> [kWh/anno]',
            delta_consumi_gdt: '\u0394ConsumiGDT[kWh / anno]',
            denominazione: 'Denominazione',
            anno_costruzione: 'Anno di costruzione',
            dimensioni_principali: 'Dimensioni principali',
            numero_motori: 'N_motori',
            potenza_motori: 'Potenza motori[kW]',
            numero_misura: 'N_misura',
            tratta_percorsa: 'Tratta percorsa(Partenza - Arrivo)',
            tipo_combustibile: 'Tipo di combustibile',
            pci_combustibile: 'PCI Combustibile Valore',
            pci_combustibile_unita_misura: 'PCI Combustibile Unit� di misura',
            densita_combustibile: 'Densit� Combustibile Valore',
            densita_unita_misura: 'Densit� Unit� di misura',
            ore_navigazione_valore: 'Ore di navigazione[h]',
            consumo_ex_post_valore: 'Consumo ex post(Valore)',
            consumo_combustibile_unita_misura: 'Consumo Combustibile(Unit� di misura)',
            velocita: 'Velocit�[knots]',
            pd: 'P / D',
            delta: '\u0394[%]',
            rea: 'REA[tep]',
            navi: 'Navi',
            ore_navigazione_header: 'Ore di navigazione',
            consumo_combustibile_header: 'Consumo di combustibile',
            velocita_header: 'Velocit�',
            compressori: 'Compressori',
            energia_elettrica: 'Energia elettrica',
            energia_elettrica_kwh: 'Energia elettrica[kWh]',
            portata_aria: 'Portata di aria',
            pressione_esercizio: 'Pressione di esercizio',
            sito_oggetto_intervento: 'Sito oggetto di intervento(Via, Citt�)',
            denominazione_sala: 'Denominazione sala',
            portata_nominale: 'Portata nominale[Nm <span class="sup" > 3 </span>/h]',
            fabbisogno_coperto: 'Fabbisogno coperto[Base / Picco]',
            n_stadi: 'N� Stadi[n�]',
            portata_nm: 'Portata[Nm <span class="sup" > 3 </span>]',
            pressione_esercizio_bar: 'Pressione di esercizio[bar]',
            rapporto_compressione_ex_ante: 'Rapporto di compressione ex ante medio \u03B2 <span class="log" > post </span>',
            progressivo_compressore_installato: 'Progressivo compressore installato',
            pressione_esercizio_nominale_bar: 'Pressione di esercizio nominale[bar]',
            energia_elettrica_consumata: 'Energia Elettrica consumata[kWh]',
            portata_erogata: 'Portata erogata[Nm <span class="sup" > 3 </span>]',
            rapporto_compressione_post: 'Rapporto di compressione post \u03B2 <span class="log" > post </span>',
        },
        empty_message: 'Nessun risultato trovato',
    },
    validazione: {
        tipo_documento_errato: 'L\'estensione del documento caricato è errata',
        caricare_documento: 'Caricare prima un documento',
    }
};
