export const text_properties = {
    title: {
        app: 'Silpha',
        ex_ante: 'EX - ANTE',
        riferimento: 'RIFERIMENTO',
        ex_post: 'EX - POST',
        dati: 'Dati',
        registrazione: 'Registrazione',
    },
    header: {
/*         sei_in: 'Sei in:',
        home: 'Home',
        next: '>>',
        certificati_bianchi: 'Certificati Bianchi', */
    },
    label: {
        carica_documento: 'Carica Fotografia',
        si: 'Si',
        no: 'No',
        nome: 'Nome',
        cognome: 'Cognome',
        email: 'Email',
        password: 'Password',
    },
    messaggio: {
        info: 'Info',
        attenzione: 'Attenzione',
        errore: 'Errore',
        errore_durante_richiesta: 'Si � verificato un errore nel processare la richiesta.',
        nessun_risultato_trovato: 'Nessun risultato trovato',
    },
    button: {
        apri: 'Apri',
        chiudi: 'Chiudi',
        annulla: 'Annulla',
        conferma: 'Conferma',
        entra: 'Entra',
        cerca: 'Cerca',
        modifica: 'Modifica',
        nuovo: 'Nuovo',
        salva: 'Salva',
        pulisci: 'Reset',
        dettaglio: 'Dettaglio',
        elimina: 'Elimina',
        applica: 'Applica',
        prosegui: 'Prosegui',
        indietro: 'Indietro',
        precedente: 'Precedente',
        successivo: 'Successivo',
        avanti: 'Avanti',
        ok: 'Ok',
        si: 'Si',
        no: 'No',
        cancella_filtri: 'Cancella Filtri',
        crea: 'Crea',
        sfoglia: 'Sfoglia...',
        salva_file: 'Salva File',
        download: 'Download',
        salva_esci: 'Salva Ed Esci',
        aggiungi: 'Aggiungi',
        carica: 'Carica',
        registrati: 'Registrati',
    },
    table: {
        col: {
        },
     empty_message: 'Nessun risultato trovato',
 },
    validazione: {

    }
};
